github_repositories:
  - name: platform-team-admin
    description: The Platform Engineer's Handbook - Repository to manage platform team membership and admin artifacts
    visibility: public
    environments:
      - name: pulumi
      - name: pulumi-production
        reviewers:
          - Jdavid77
  - name: platform-core
    description: The Platform Engineer's Handbook - Core platform runtime
    visibility: public
    environments:
      - name: platform-sandbox
        reviewers:
          - Jdavid77
      - name: app-dev
        reviewers:
          - Jdavid77
  - name: platform-demo-apps
    description: The Platform Engineer's Handbook - Demo application for testing the platform
    visibility: public
  - name: platform-gitops
    description: The Platform Engineer's Handbook - FluxCD Repository used to manage all of the deployments
    visibility: public

# github_organization_members:
#   - name: Team Member
#     github-role: admin
#     github-username: team_member
#     email: team_member@email.com
