github_repositories:
  - name: platform-team-admin
    description: Repository to manage platform team membership and admin artifacts
  - name: platform-core
    description: Core platform runtime
  - name: platform-demo-apps
    description: Demo application for testing the platform

# github_organization_members:
#   - name: Team Member
#     github-role: admin
#     github-username: team_member
#     email: team_member@email.com