name: Pulumi Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main

jobs:
  pulumi-preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: pulumi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v5

      - run: uv sync

      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: Jdavid77/platformteamadministration/dev
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  approve-deployment:
    needs: pulumi-preview
    runs-on: ubuntu-latest
    environment: pulumi-production
    steps:
      - run: echo "Deployment approved"

  pulumi-up:
    needs: approve-deployment
    runs-on: ubuntu-latest
    environment: pulumi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v5

      - run: uv sync

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: Jdavid77/platformteamadministration/dev
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
